// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tprdfzcbackwywhdxere.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcmRmemNiYWNrd3l3aGR4ZXJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MTQ4ODgsImV4cCI6MjA3Mzk5MDg4OH0.M_xoBqvcbdNA6LABig_E1b_haWlKKU5qo828OsnHDeM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});